apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: microceph-rbd
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "61b9808c-9b4c-4941-ace2-6f1a8d0eca54"
  pool: "rbd"
  imageFeatures: "layering"
  csi.storage.k8s.io/provisioner-secret-name: "ceph-admin-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "ceph-csi-rbd-system"
  csi.storage.k8s.io/node-stage-secret-name: "ceph-admin-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "ceph-csi-rbd-system"
  monitors: "192.168.0.9:6789,192.168.0.8:6789,192.168.0.7:6789,192.168.0.15:6789"
reclaimPolicy: Delete
allowVolumeExpansion: true


# # 1. Remove a versão antiga/com erro para liberar os campos imutáveis
# kubectl delete storageclass microceph-rbd --ignore-not-found

# 2. Aplica a versão declarativa limpa
# kubectl apply -f ceph_storageclass.yaml