apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - self-healing-complete.yaml

secretGenerator:
  - name: dashboard-credentials
    literals:
      - DASH_USER=admin
      - DASH_PASS=MinhaSenhaSuperSegura123
